color desert
set background=dark
syntax enable
filetype plugin on

" set font size
set guifont=Monaco:h14

" Use spaces instead of tabs
set expandtab

" 1 tab == 2 spaces
set shiftwidth=2
set tabstop=2

" show line number
set relativenumber

" search ignore case
set ignorecase

" syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" Source plugins with vundle
if filereadable(expand("~/.vim/plugins.vim"))
  source ~/.vim/plugins.vim
endif

" Source key map
source ~/.vim/map.vim
