"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
${env_var.ZMX_SESSION}\
$directory\
$git_branch\
$git_state\
$git_status\
$docker_context\
$golang\
$nodejs\
$ruby\
$zig\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$container\
$character\
"""

[status]
disabled = false

[directory]
truncate_to_repo = false

[env_var.ZMX_SESSION]
symbol = " "
format = "[$symbol$env_value]($style) "
description = "zmx session name"
style = "bold green"
