"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$docker_context\
$golang\
$nodejs\
$ruby\
$zig\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$container\
$character\
"""

[status]
disabled = false

[directory]
truncate_to_repo = false
