import = [
    "~/.config/alacritty/themes/nord.toml"
]

[shell]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
decorations = "Buttonless"

[scrolling]
history = 100000

[font]
size = 15
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[env]
TERM = "xterm-256color"
