[tools]
go = "latest"
node = "24"
ruby = "latest"
zig = "latest"

# Treesitter
tree-sitter = "latest"

# LSP
# Bash
"npm:bash-language-server" = "latest"
# Docker
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
# HTML/CSS/JSON/ESLint
"npm:vscode-langservers-extracted" = "latest"
# Go
"go:golang.org/x/tools/gopls" = "latest"
"aqua:golangci-lint" = "latest"
# Lua
"aqua:LuaLS/lua-language-server" = "latest"
# Markdown
marksman = "latest"
# SQL
"npm:sql-language-server" = "latest"
# YAML
"npm:yaml-language-server" = "latest"
# Zig
"zls" = "latest"

[settings.ruby]
compile = false
